version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - CHROMA_PERSIST_DIRECTORY=/app/chroma_db
    volumes:
      - ./backend:/app
      - chroma_data:/app/chroma_db
    depends_on:
      - chroma
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - app-network

volumes:
  chroma_data:

networks:
  app-network:
    driver: bridge
