name: Deploy AI Chatbot to EC2

on:
  push:
    branches:
      - ec2-backup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup SSH with your private key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Deploy to EC2
      - name: Run deploy script on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            # Go to your project folder
            cd ~/ai-chatbot || exit

            # Pull latest code
            git fetch origin
            git checkout ec2-backup
            git reset --hard origin/ec2-backup

            # Rebuild & restart only backend and frontend
            docker-compose build backend frontend
            docker-compose up -d backend frontend
          EOF
